#!/bin/bash
echo "🚀 最终尝试GitLab上传"
echo "时间: $(date)"
echo "项目: project-management-system"
echo "目标: GitLab (gitlab.cihon.cn)"
echo ""

echo "=== 选项1：SSH方案 ==="
echo "1. 测试SSH连接："
echo "   ssh -i ~/.ssh/id_rsa_gitlab_cihon -T git@gitlab.cihon.cn"
echo ""
echo "2. 如果SSH成功，推送代码："
echo "   git remote set-url gitlab-ssh git@gitlab.cihon.cn:whl_openclaw/project-management-system.git"
echo "   git push gitlab-ssh main --force"
echo ""

echo "=== 选项2：HTTPS+令牌方案 ==="
echo "1. 获取GitLab访问令牌（如果还没有）："
echo "   登录 https://gitlab.cihon.cn"
echo "   头像 → Edit profile → Access Tokens"
echo "   创建新令牌，勾选 api, read_repository, write_repository"
echo "   复制令牌：glpat-xxxxxxxxxxxxxxxxxxxx"
echo ""
echo "2. 使用令牌推送："
echo "   ./紧急令牌上传.sh <你的令牌>"
echo ""

echo "=== 选项3：码云备份 ==="
echo "如果GitLab持续失败，使用码云："
echo "   ./执行HTTPS推送.sh"
echo "   输入码云账号密码"
echo ""

echo "=== 选项4：本地备份 ==="
echo "创建本地代码备份："
echo "   tar -czf project-management-system-backup-\$(date +%Y%m%d_%H%M).tar.gz ."
echo ""

echo "🎯 建议执行顺序："
echo "1. 先尝试SSH方案（最快）"
echo "2. 如果失败，立即使用HTTPS+令牌"
echo "3. 如果还失败，使用码云备份"
echo "4. 最后创建本地备份"
echo ""

echo "⏱️ 时间紧迫！必须在22:15前完成至少一种上传！"
echo "🚀 立即执行！"
