#!/bin/bash
# 个人工作详情查询脚本

echo "🔍 个人工作详情查询"
echo ""

if [ $# -eq 0 ]; then
    echo "可用查询参数:"
    echo "  张工     - 架构师工作"
    echo "  李工     - 用户管理模块"
    echo "  王工     - 项目管理模块"
    echo "  赵工     - 任务管理模块"
    echo "  孙工     - 工时管理模块"
    echo "  郑工     - 项目经理"
    echo "  钱工     - 产品经理"
    echo "  杨工     - 测试经理"
    echo "  吴工     - 运维工程师"
    echo "  文档工   - 文档工程师"
    echo "  all      - 所有人工作"
    echo ""
    echo "示例: ./查询个人工作详情.sh 张工"
    exit 0
fi

PERSON=$1

case $PERSON in
    "张工")
        echo "=== 张工 - 架构师 ==="
        echo "工作内容:"
        echo "  - 技术架构设计"
        echo "  - 框架选型和集成"
        echo "  - 代码规范和审查"
        echo "  - 性能优化指导"
        echo ""
        echo "完成情况:"
        echo "  ✅ 设计基于RuoYi的架构方案"
        echo "  ✅ 完成backend结构重组"
        echo "  ✅ 制定开发规范和标准"
        echo "  ✅ 代码审查和质量控制"
        echo "  ✅ 技术方案文档编写"
        echo ""
        echo "产出成果:"
        echo "  - backend/ 目录结构重组"
        echo "  - 技术方案文档 (Feishu链接)"
        echo "  - 开发规范.md"
        echo "  - 代码审查报告.md"
        ;;
    
    "李工")
        echo "=== 李工 - 用户管理模块开发 ==="
        echo "工作内容:"
        echo "  - 用户管理功能开发"
        echo "  - 权限系统实现"
        echo "  - 登录认证系统"
        echo "  - 安全控制"
        echo ""
        echo "完成情况:"
        echo "  ✅ 用户实体类设计"
        echo "  ✅ 基础CRUD接口"
        echo "  ⚠️ 权限控制开发中"
        echo "  ⚠️ 登录认证开发中"
        echo ""
        echo "代码产出:"
        echo "  - backend/ruoyi/ruoyi-system/ 相关模块"
        echo "  - 用户管理API接口"
        echo "  - 权限控制逻辑"
        ;;
    
    "王工")
        echo "=== 王工 - 项目管理模块开发 ==="
        echo "工作内容:"
        echo "  - 项目管理功能开发"
        echo "  - 项目状态管理"
        echo "  - 项目成员分配"
        echo "  - 项目统计报表"
        echo ""
        echo "完成情况:"
        echo "  ✅ 项目实体类设计 (Project.java)"
        echo "  ✅ 项目控制器开发 (ProjectController.java)"
        echo "  ✅ 项目服务接口 (IProjectService.java)"
        echo "  ⚠️ 项目业务逻辑开发中"
        echo ""
        echo "代码产出:"
        echo "  - backend/project/ 目录完整模块"
        echo "  - 项目管理核心类"
        echo "  - 项目相关API接口"
        ;;
    
    "赵工")
        echo "=== 赵工 - 任务管理模块开发 ==="
        echo "工作内容:"
        echo "  - 任务管理功能开发"
        echo "  - 任务状态流转"
        echo "  - 任务优先级管理"
        echo "  - 任务分配和跟踪"
        echo ""
        echo "完成情况:"
        echo "  ✅ 任务实体类设计 (Task.java)"
        echo "  ⚠️ 任务控制器开发中"
        echo "  ⚠️ 任务服务开发中"
        echo "  ⚠️ 任务状态机实现中"
        echo ""
        echo "代码产出:"
        echo "  - backend/task/ 目录基础结构"
        echo "  - 任务实体类"
        echo "  - 任务数据库表设计"
        ;;
    
    "孙工")
        echo "=== 孙工 - 工时管理模块开发 ==="
        echo "工作内容:"
        echo "  - 工时记录功能开发"
        echo "  - 工时审批流程"
        echo "  - 工时统计报表"
        echo "  - 薪资计算基础"
        echo ""
        echo "完成情况:"
        echo "  ✅ 工时实体类设计 (WorkHour.java)"
        echo "  ⚠️ 工时控制器开发中"
        echo "  ⚠️ 工时服务开发中"
        echo "  ⚠️ 审批流程设计"
        echo ""
        echo "代码产出:"
        echo "  - backend/workhour/ 目录基础结构"
        echo "  - 工时实体类"
        echo "  - 工时数据库表设计"
        ;;
    
    "郑工")
        echo "=== 郑工 - 项目经理 ==="
        echo "工作内容:"
        echo "  - 项目整体规划和管理"
        echo "  - 进度跟踪和风险控制"
        echo "  - 团队协调和资源分配"
        echo "  - 质量监控和验收"
        echo ""
        echo "完成情况:"
        echo "  ✅ 制定详细项目研发计划表"
        echo "  ✅ 创建小时级开发计划"
        echo "  ✅ 建立问题跟踪机制"
        echo "  ✅ 协调21人团队分工"
        echo "  ✅ 监控项目进度和质量"
        echo "  ⚠️ 当前跟踪核心功能开发进度"
        echo ""
        echo "产出文档:"
        echo "  - 项目研发计划表.md"
        echo "  - 小时级开发计划.md"
        echo "  - 问题跟踪看板.md"
        echo "  - 紧急协调通知.md"
        ;;
    
    "钱工")
        echo "=== 钱工 - 产品经理 ==="
        echo "工作内容:"
        echo "  - 需求分析和产品设计"
        echo "  - 原型设计和功能规划"
        echo "  - 用户验收和反馈收集"
        echo "  - 产品文档编写"
        echo ""
        echo "完成情况:"
        echo "  ✅ 完成完整PRD文档"
        echo "  ✅ 设计产品原型"
        echo "  ✅ 制定功能规格"
        echo "  ✅ 创建用户故事"
        echo "  ⚠️ 准备用户验收测试"
        echo ""
        echo "产出文档:"
        echo "  - PRD文档 (Feishu链接)"
        echo "  - 产品原型 (Feishu链接)"
        echo "  - 功能规格说明书"
        echo "  - 用户故事地图"
        ;;
    
    "杨工")
        echo "=== 杨工 - 测试经理 ==="
        echo "工作内容:"
        echo "  - 测试计划制定"
        echo "  - 测试用例设计"
        echo "  - 质量保障体系"
        echo "  - 测试报告编写"
        echo ""
        echo "完成情况:"
        echo "  ✅ 测试计划制定"
        echo "  ✅ 测试用例设计"
        echo "  ✅ 质量检查点设置"
        echo "  ⚠️ 测试执行监控中"
        echo ""
        echo "产出文档:"
        echo "  - 测试用例-详细版.xlsx.md"
        echo "  - 测试执行指南.md"
        echo "  - 质量保障检查.sh"
        echo "  - 测试报告模板"
        ;;
    
    "吴工")
        echo "=== 吴工 - 运维工程师 ==="
        echo "工作内容:"
        echo "  - 开发环境部署"
        echo "  - 系统监控设置"
        echo "  - 备份和恢复"
        echo "  - 性能优化"
        echo ""
        echo "完成情况:"
        echo "  ✅ MySQL数据库安装配置"
        echo "  ✅ 开发环境脚本创建"
        echo "  ✅ 监控工具配置"
        echo "  ✅ 备份方案制定"
        echo ""
        echo "产出工具:"
        echo "  - 一键启动.sh / 一键停止.sh"
        echo "  - 环境检查.sh"
        echo "  - 数据库管理.sh"
        echo "  - 监控配置脚本"
        ;;
    
    "文档工")
        echo "=== 文档工 - 文档工程师 ==="
        echo "工作内容:"
        echo "  - 技术文档编写"
        echo "  - 用户手册创建"
        echo "  - API文档生成"
        echo "  - 项目文档管理"
        echo ""
        echo "完成情况:"
        echo "  ✅ 技术文档体系建立"
        echo "  ✅ 用户手册框架"
        echo "  ✅ API文档模板"
        echo "  ✅ 项目文档索引"
        echo ""
        echo "产出文档:"
        echo "  - README.md 项目总览"
        echo "  - 文件索引.md 完整索引"
        echo "  - 各类技术文档"
        echo "  - 用户操作指南"
        ;;
    
    "all")
        echo "显示所有人工作摘要..."
        echo ""
        echo "📊 21人团队工作摘要:"
        echo "1. 项目管理组 (2人): 计划制定和进度跟踪完成"
        echo "2. 产品管理组 (1人): PRD和原型设计完成"
        echo "3. 后端开发组 (12人): 架构和基础模块完成，业务逻辑开发中"
        echo "4. 前端开发组 (6人): 项目框架完成，界面开发中"
        echo "5. 测试组 (3人): 测试计划完成，测试执行中"
        echo "6. 运维组 (1人): 环境配置完成"
        echo "7. 文档组 (1人): 文档体系建立"
        echo ""
        echo "详细报告查看: 团队工作完成情况汇报.md"
        ;;
    
    *)
        echo "❌ 未找到人员: $PERSON"
        echo "可用人员: 张工, 李工, 王工, 赵工, 孙工, 郑工, 钱工, 杨工, 吴工, 文档工, all"
        ;;
esac
